version: '3'

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBURL}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DBURL}
      SPRING_DATASOURCE_USERNAME: ${DBNAME}
      SPRING_DATASOURCE_PASSWORD: ${DBPASS}

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: