# name: Deploy to Server

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up JDK 21
#         uses: actions/setup-java@v2
#         with:
#           java-version: '21'
#           distribution: 'adopt'

#       - name: Build Backend
#         run: |
#           cd backend 
#           mvn clean package -DskipTests

#       - name: Build Frontend
#         run: |
#           cd frontend
#           npm install
#           npm run build

#       - name: Deploy via SSH
#         run: |
#           ssh ubuntu@162.19.231.97 'rm -rf /usr/share/nginx/html/*'
#           scp -r * ubuntu@162.19.231.97:/usr/share/nginx/html/